// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suajkyisviujftusfbbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1YWpreWlzdml1amZ0dXNmYmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTM5MDEsImV4cCI6MjA2MTIyOTkwMX0.CMwXwtVf2IvlLA9iny7YtvWZBbQsBA_dAm-hvbJvt4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);